### ISSUE TITLE
Scroll to top after page load.

### ISSUE THREAD

**Issue by jacopobonomi** [majick777/teleporter#5]
There is an option to scroll to top after child page load?

**Comment by majick777** [comment]
@jacopobonomi It doesn't have this option yet, I'm not sure under what circumstance you'd want it to do that?
If it's a new child page why would it not be at the top of the page already? 
And if it's an existing child page that's already loaded, you would lose your current position on that page.

**Comment by jacopobonomi** [comment]
Hey  @majick777  when i go to new child page, plugin add to url "https://example.url/#first-id", and scroll to first element with id. I can give you in private url of an example.

**Comment by majick777** [comment]
@jacopobonomi part of the intention with Teleporter is to have it mimic what normal browser behaviour would be. you can still use #hash jump links in an URL as normal... so I'm not sure when and why you'd want to change the default behaviour to scroll to the top when you can still do that with individual links?

**Comment by jacopobonomi** [comment]
My problem is that, when i click for example in a product of woocommerce with normal url like
"x.xyz/product/test", with Teleporter active, browser redirect to "x.xyx/product/test#additional-tab" and the page scroll down.
